
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlabsxcfgtiqmktltvbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsYWJzeGNmZ3RpcW1rdGx0dmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzE3OTcsImV4cCI6MjA1OTM0Nzc5N30.NQJUG3AGFcyzEqldKWTeCVHFT_saGQ_fTRCUGK1vOMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
